function(print_string str)
  message("str=${str}")
endfunction(print_string)

function(print_message)
  # 为了分行确定输出内容
  message("**********************************************************")
  message("-1.PROJECT_NAME = ${PROJECT_NAME}")
  message("0.CMAKE_SOURCE_DIR =
${CMAKE_SOURCE_DIR}")
  message("1.PROJECT_BINARY_DIR = ${PROJECT_BINARY_DIR}")
  message("2.PROJECT_SOURCE _DIR = ${PROJECT_SOURCE_DIR}")
  message("3.CMAKE_CURRENT_SOURCE_DIR = ${CMAKE_CURRENT_SOURCE_DIR}")
  message("4.CMAKE_CURRENT_BINARY_DIR = ${CMAKE_CURRENT_BINARY_DIR}")
  message("4.CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG =
${CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG}")
  message("5.CMAKE_CURRENT_LIST_FILE =
${CMAKE_CURRENT_LIST_FILE}")
  message("6.CMAKE_CURRENT_LIST_LINE =
${CMAKE_CURRENT_LIST_LINE}")
  message("7.CMAKE_MODULE_PATH =
${CMAKE_MODULE_PATH}")
  message("8.CMAKE_SOURCE_DIR = ${CMAKE_SOURCE_DIR}")
  message("9.EXECUTABLE_OUTPUT_PATH = ${EXECUTABLE_OUTPUT_PATH}")
  message("10.LIBRARY_OUTPUT_PATH = ${LIBRARY_OUTPUT_PATH}")
  message("11.PROJECT_NAME = ${PROJECT_NAME}")
  message("12.CMAKE_SOURCE_DIR =
${CMAKE_SOURCE_DIR}")
  message("13.PROJECT_VERSION_MINOR =
${PROJECT_VERSION_MINOR}")
  message("14.PROJECT_VERSION_PATCH =
${PROJECT_VERSION_PATCH}")
  message("15.CMAKE_SYSTEM = ${CMAKE_SYSTEM}")
  message("16.CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
  message("17.CMAKE_SYSTEM_VERSION = ${CMAKE_SYSTEM_VERSION}")
  message("18.BUILD_SHARED_LIBS = ${BUILD_SHARED_LIBS}")
  message("19.CMAKE_C_FLAGS = ${CMAKE_C_FLAGS}")
  message("20.CMAKE_CXX_FLAGS =
${CMAKE_CXX_FLAGS}")
  message("21.CMAKE_SYSTEM_PROCESSOR   =
${CMAKE_SYSTEM_PROCESSOR}")
  message("22.CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG =
${CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG}")
  message("23.CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE =
${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE}")
  message("**********************************************************")
endfunction(print_message)